# Cessna 172 Skyhawk Configuration
# Realistic configuration for the popular Cessna 172 training aircraft

aircraft:
  name: "Cessna 172 Skyhawk"
  icao_code: "C172"
  manufacturer: "Cessna"

  # Flight model configuration
  flight_model: "Simple6DOF"
  flight_model_config:
    wing_area_sqft: 174.0        # Wing area in square feet
    weight_lbs: 2450.0            # Empty weight + pilot + fuel
    max_thrust_lbs: 180.0         # Maximum thrust from engine (HP converted)
    drag_coefficient: 0.027       # Cd0 - zero-lift drag coefficient
    lift_coefficient_slope: 0.09  # Cl_alpha - lift curve slope

  # Aircraft systems plugins
  plugins:
    # Piston engine - Lycoming O-360
    - plugin: "simple_piston_engine"
      instance_id: "engine"
      config:
        max_power_hp: 180           # 180 HP Lycoming O-360
        max_rpm: 2700               # Maximum RPM
        idle_rpm: 600               # Idle RPM
        fuel_consumption_base_gph: 9.5  # Base fuel consumption at full power
        displacement_liters: 5.9    # Engine displacement
        cylinders: 4                # Number of cylinders
        aspiration: "naturally_aspirated"
        # Starter motor requirements (configurable for different aircraft)
        starter_min_voltage: 11.0   # Minimum battery voltage to engage starter
        starter_current_draw: 150.0 # Starter motor current draw in amps
        requires_fuel: true         # Whether fuel must be available to start
        requires_magnetos: true     # Whether magnetos must be on to start

    # Electrical system - 28V system
    - plugin: "simple_electrical_system"
      instance_id: "electrical"
      config:
        battery_voltage: 12.6       # 12V lead-acid battery (resting voltage)
        battery_capacity_ah: 35.0   # 35 Ah capacity
        alternator_voltage: 14.0    # Regulated alternator voltage
        alternator_amps: 60.0       # 60A alternator
        base_load_amps: 5.0         # Base electrical load

    # Fuel system - Two wing tanks
    - plugin: "simple_fuel_system"
      instance_id: "fuel"
      config:
        left_tank_capacity: 26.0    # Left tank capacity in gallons
        right_tank_capacity: 26.0   # Right tank capacity in gallons
        unusable_fuel: 2.0          # Unusable fuel per tank
        fuel_selector: "both"       # Initial selector position

  # Electrical system detailed configuration
  electrical:
    implementation: "simple_12v"
    battery:
      voltage_nominal: 12.6        # Fully charged resting voltage (lead-acid)
      capacity_ah: 35.0             # Total battery capacity in amp-hours
      internal_resistance: 0.05     # Internal resistance in ohms
    alternator:
      max_amps: 60.0                # Maximum alternator output current
      voltage_regulated: 14.0       # Regulated charging voltage
      rpm_threshold: 800            # Minimum engine RPM to produce power
    loads:
      master_relay:
        amps: 0.1
        essential: true
        min_voltage: 10.0
      starter_motor:
        amps: 150.0
        essential: true
        min_voltage: 11.0
      fuel_pump:
        amps: 5.0
        essential: false
        min_voltage: 10.0
      avionics:
        amps: 10.0
        essential: false
        min_voltage: 11.5
      nav_lights:
        amps: 1.5
        essential: false
        min_voltage: 10.0
      beacon:
        amps: 2.0
        essential: false
        min_voltage: 10.0
      strobe:
        amps: 3.0
        essential: false
        min_voltage: 10.0
      taxi_light:
        amps: 4.0
        essential: false
        min_voltage: 10.0
      landing_light:
        amps: 8.0
        essential: false
        min_voltage: 10.0
      pitot_heat:
        amps: 7.0
        essential: false
        min_voltage: 10.0

  # Fuel system detailed configuration
  fuel:
    implementation: "simple_gravity"
    fuel_type: "avgas_100ll"
    lbs_per_gallon: 6.0
    tanks:
      left:
        capacity_total: 28.0        # Total tank capacity (including unusable)
        capacity_usable: 26.0       # Usable fuel capacity
        initial_quantity: 26.0      # Start with full usable fuel
        fuel_type: "avgas_100ll"
        position: [-5.0, 0.0, -8.0] # Relative to CG (x, y, z in feet)
      right:
        capacity_total: 28.0
        capacity_usable: 26.0
        initial_quantity: 26.0
        fuel_type: "avgas_100ll"
        position: [-5.0, 0.0, 8.0]
    selector_positions: [OFF, LEFT, RIGHT, BOTH]

  # Audio configuration
  audio:
    engine_sounds:
      running: "assets/sounds/aircraft/ef3_engine.wav"  # Eurofly 3 engine recording
      pitch_idle: 0.7       # Audio pitch at 0% throttle
      pitch_full: 1.3       # Audio pitch at 100% throttle
    click_sounds:
      switch_on: "assets/sounds/aircraft/click_switch_on.mp3"
      switch_off: "assets/sounds/aircraft/click_switch_off.mp3"
      button: "assets/sounds/aircraft/click_button.mp3"
      knob: "assets/sounds/aircraft/click_knob.mp3"
    system_sounds:
      battery_on: "assets/sounds/aircraft/batteryon1.mp3"
      battery_off: "assets/sounds/aircraft/batteryoff1.mp3"
      battery_loop: "assets/sounds/aircraft/batteryloop1.mp3"
      fuel_pump: "assets/sounds/aircraft/fuelpump1.mp3"

  # Weight and balance configuration
  weight_balance:
    empty_weight: 1600.0            # Empty aircraft weight (lbs)
    empty_moment: 136000.0          # Empty aircraft moment (lb-in, CG ~85 inches)
    max_gross_weight: 2550.0        # Maximum gross weight (lbs)
    cg_limits:
      forward: 82.9                 # Forward CG limit (inches from datum)
      aft: 95.5                     # Aft CG limit (inches from datum)
    stations:
      fuel_tanks:
        - name: "main_tank"         # Combined fuel tanks for simplicity
          arm: 95.0                 # Arm position (inches from datum)
          max_weight: 312.0         # Max fuel weight (52 gal × 6 lb/gal)
          initial_weight: 312.0     # Start with full tanks
      seats:
        - name: "seat_pilot"
          arm: 85.0                 # Front seat arm
          max_weight: 200.0         # Max pilot + baggage
          initial_weight: 200.0     # Start with pilot
        - name: "seat_copilot"
          arm: 85.0                 # Front seat arm
          max_weight: 200.0         # Max copilot + baggage
          initial_weight: 0.0       # Start empty
        - name: "seat_rear_left"
          arm: 118.0                # Rear seat arm
          max_weight: 200.0         # Max passenger + baggage
          initial_weight: 0.0       # Start empty
        - name: "seat_rear_right"
          arm: 118.0                # Rear seat arm
          max_weight: 200.0         # Max passenger + baggage
          initial_weight: 0.0       # Start empty
      cargo:
        - name: "cargo_bay"
          arm: 142.0                # Baggage area arm
          max_weight: 120.0         # Max baggage weight
          initial_weight: 0.0       # Start empty

  # Initial state
  initial_state:
    position:
      latitude: 37.615223          # San Francisco area
      longitude: -122.389977
      altitude_ft: 0                # On ground
    fuel:
      left_tank_gallons: 26.0       # Start with full tanks
      right_tank_gallons: 26.0
    electrical:
      battery_master: false         # Start with battery off
      alternator_switch: false      # Start with alternator off
    engine:
      running: false                # Engine not running
      mixture: 1.0                  # Full rich
      throttle: 0.0                 # Idle
