# English Speech Messages Configuration
# Maps message keys to audio filenames (without extension)
# Format: MESSAGE_KEY: "filename_without_extension"

language: en
file_extension: mp3

# System messages
messages:
  # Startup
  MSG_STARTUP: "airborne_flight_simulator"
  MSG_READY: "ready_for_flight"
  MSG_ERROR: "error"
  MSG_ERROR_MESSAGE: "error_message"
  MSG_NOT_FOUND: "message_not_found"

  # Action confirmations
  MSG_GEAR_DOWN: "gear_down"
  MSG_GEAR_UP: "gear_up"
  MSG_FLAPS_EXTENDING: "flaps_extending"
  MSG_FLAPS_RETRACTING: "flaps_retracting"
  MSG_THROTTLE_INCREASED: "throttle_increased"
  MSG_THROTTLE_DECREASED: "throttle_decreased"
  MSG_FULL_THROTTLE: "full_throttle"
  MSG_THROTTLE_IDLE: "throttle_idle"
  MSG_BRAKES_ON: "brakes_on"
  MSG_PAUSED: "paused"
  MSG_NEXT: "next"

  # Airspeed readouts (0-300 knots in 5-knot increments)
  MSG_AIRSPEED_0: "0_knots"
  MSG_AIRSPEED_5: "5_knots"
  MSG_AIRSPEED_10: "10_knots"
  MSG_AIRSPEED_15: "15_knots"
  MSG_AIRSPEED_20: "20_knots"
  MSG_AIRSPEED_25: "25_knots"
  MSG_AIRSPEED_30: "30_knots"
  MSG_AIRSPEED_35: "35_knots"
  MSG_AIRSPEED_40: "40_knots"
  MSG_AIRSPEED_45: "45_knots"
  MSG_AIRSPEED_50: "50_knots"
  MSG_AIRSPEED_55: "55_knots"
  MSG_AIRSPEED_60: "60_knots"
  MSG_AIRSPEED_65: "65_knots"
  MSG_AIRSPEED_70: "70_knots"
  MSG_AIRSPEED_75: "75_knots"
  MSG_AIRSPEED_80: "80_knots"
  MSG_AIRSPEED_85: "85_knots"
  MSG_AIRSPEED_90: "90_knots"
  MSG_AIRSPEED_95: "95_knots"
  MSG_AIRSPEED_100: "100_knots"
  MSG_AIRSPEED_105: "105_knots"
  MSG_AIRSPEED_110: "110_knots"
  MSG_AIRSPEED_115: "115_knots"
  MSG_AIRSPEED_120: "120_knots"
  MSG_AIRSPEED_125: "125_knots"
  MSG_AIRSPEED_130: "130_knots"
  MSG_AIRSPEED_135: "135_knots"
  MSG_AIRSPEED_140: "140_knots"
  MSG_AIRSPEED_145: "145_knots"
  MSG_AIRSPEED_150: "150_knots"
  MSG_AIRSPEED_155: "155_knots"
  MSG_AIRSPEED_160: "160_knots"
  MSG_AIRSPEED_165: "165_knots"
  MSG_AIRSPEED_170: "170_knots"
  MSG_AIRSPEED_175: "175_knots"
  MSG_AIRSPEED_180: "180_knots"
  MSG_AIRSPEED_185: "185_knots"
  MSG_AIRSPEED_190: "190_knots"
  MSG_AIRSPEED_195: "195_knots"
  MSG_AIRSPEED_200: "200_knots"
  MSG_AIRSPEED_205: "205_knots"
  MSG_AIRSPEED_210: "210_knots"
  MSG_AIRSPEED_215: "215_knots"
  MSG_AIRSPEED_220: "220_knots"
  MSG_AIRSPEED_225: "225_knots"
  MSG_AIRSPEED_230: "230_knots"
  MSG_AIRSPEED_235: "235_knots"
  MSG_AIRSPEED_240: "240_knots"
  MSG_AIRSPEED_245: "245_knots"
  MSG_AIRSPEED_250: "250_knots"
  MSG_AIRSPEED_255: "255_knots"
  MSG_AIRSPEED_260: "260_knots"
  MSG_AIRSPEED_265: "265_knots"
  MSG_AIRSPEED_270: "270_knots"
  MSG_AIRSPEED_275: "275_knots"
  MSG_AIRSPEED_280: "280_knots"
  MSG_AIRSPEED_285: "285_knots"
  MSG_AIRSPEED_290: "290_knots"
  MSG_AIRSPEED_295: "295_knots"
  MSG_AIRSPEED_300: "300_knots"

  # Altitude readouts
  MSG_ALTITUDE_0: "0_feet"
  MSG_ALTITUDE_100: "100_feet"
  MSG_ALTITUDE_200: "200_feet"
  MSG_ALTITUDE_300: "300_feet"
  MSG_ALTITUDE_400: "400_feet"
  MSG_ALTITUDE_500: "500_feet"
  MSG_ALTITUDE_1000: "1000_feet"
  MSG_ALTITUDE_1500: "1500_feet"
  MSG_ALTITUDE_2000: "2000_feet"
  MSG_ALTITUDE_2500: "2500_feet"
  MSG_ALTITUDE_3000: "3000_feet"
  MSG_ALTITUDE_4000: "4000_feet"
  MSG_ALTITUDE_5000: "5000_feet"
  MSG_ALTITUDE_6000: "6000_feet"
  MSG_ALTITUDE_7000: "7000_feet"
  MSG_ALTITUDE_8000: "8000_feet"
  MSG_ALTITUDE_9000: "9000_feet"
  MSG_ALTITUDE_10000: "10000_feet"
  MSG_ALTITUDE_12000: "12000_feet"
  MSG_ALTITUDE_15000: "15000_feet"
  MSG_ALTITUDE_20000: "20000_feet"

  # Heading readouts (0-350 in 10-degree increments, using aviation phraseology)
  MSG_HEADING_0: "heading_zero_zero_zero"
  MSG_HEADING_10: "heading_zero_one_zero"
  MSG_HEADING_20: "heading_zero_two_zero"
  MSG_HEADING_30: "heading_zero_three_zero"
  MSG_HEADING_40: "heading_zero_four_zero"
  MSG_HEADING_50: "heading_zero_five_zero"
  MSG_HEADING_60: "heading_zero_six_zero"
  MSG_HEADING_70: "heading_zero_seven_zero"
  MSG_HEADING_80: "heading_zero_eight_zero"
  MSG_HEADING_90: "heading_zero_niner_zero"
  MSG_HEADING_100: "heading_one_zero_zero"
  MSG_HEADING_110: "heading_one_one_zero"
  MSG_HEADING_120: "heading_one_two_zero"
  MSG_HEADING_130: "heading_one_three_zero"
  MSG_HEADING_140: "heading_one_four_zero"
  MSG_HEADING_150: "heading_one_five_zero"
  MSG_HEADING_160: "heading_one_six_zero"
  MSG_HEADING_170: "heading_one_seven_zero"
  MSG_HEADING_180: "heading_one_eight_zero"
  MSG_HEADING_190: "heading_one_niner_zero"
  MSG_HEADING_200: "heading_two_zero_zero"
  MSG_HEADING_210: "heading_two_one_zero"
  MSG_HEADING_220: "heading_two_two_zero"
  MSG_HEADING_230: "heading_two_three_zero"
  MSG_HEADING_240: "heading_two_four_zero"
  MSG_HEADING_250: "heading_two_five_zero"
  MSG_HEADING_260: "heading_two_six_zero"
  MSG_HEADING_270: "heading_two_seven_zero"
  MSG_HEADING_280: "heading_two_eight_zero"
  MSG_HEADING_290: "heading_two_niner_zero"
  MSG_HEADING_300: "heading_three_zero_zero"
  MSG_HEADING_310: "heading_three_one_zero"
  MSG_HEADING_320: "heading_three_two_zero"
  MSG_HEADING_330: "heading_three_three_zero"
  MSG_HEADING_340: "heading_three_four_zero"
  MSG_HEADING_350: "heading_three_five_zero"

  # Vertical speed
  MSG_LEVEL_FLIGHT: "level_flight"
  MSG_CLIMBING_100: "100_climbing"
  MSG_CLIMBING_200: "200_climbing"
  MSG_CLIMBING_300: "300_climbing"
  MSG_CLIMBING_500: "500_climbing"
  MSG_CLIMBING_1000: "1000_climbing"
  MSG_CLIMBING_1500: "1500_climbing"
  MSG_CLIMBING_2000: "2000_climbing"
  MSG_DESCENDING_100: "100_descending"
  MSG_DESCENDING_200: "200_descending"
  MSG_DESCENDING_300: "300_descending"
  MSG_DESCENDING_500: "500_descending"
  MSG_DESCENDING_1000: "1000_descending"
  MSG_DESCENDING_1500: "1500_descending"
  MSG_DESCENDING_2000: "2000_descending"

  # Attitude (concise format)
  MSG_LEVEL_ATTITUDE: "level"
  MSG_PITCH_5_UP: "5_up"
  MSG_PITCH_10_UP: "10_up"
  MSG_PITCH_15_UP: "15_up"
  MSG_PITCH_20_UP: "20_up"
  MSG_PITCH_30_UP: "30_up"
  MSG_PITCH_45_UP: "45_up"
  MSG_PITCH_5_DOWN: "5_down"
  MSG_PITCH_10_DOWN: "10_down"
  MSG_PITCH_15_DOWN: "15_down"
  MSG_PITCH_20_DOWN: "20_down"
  MSG_PITCH_30_DOWN: "30_down"
  MSG_PITCH_45_DOWN: "45_down"
  MSG_BANK_5_LEFT: "5_left"
  MSG_BANK_10_LEFT: "10_left"
  MSG_BANK_15_LEFT: "15_left"
  MSG_BANK_20_LEFT: "20_left"
  MSG_BANK_30_LEFT: "30_left"
  MSG_BANK_45_LEFT: "45_left"
  MSG_BANK_5_RIGHT: "5_right"
  MSG_BANK_10_RIGHT: "10_right"
  MSG_BANK_15_RIGHT: "15_right"
  MSG_BANK_20_RIGHT: "20_right"
  MSG_BANK_30_RIGHT: "30_right"
  MSG_BANK_45_RIGHT: "45_right"

  # ATC Menu messages
  MSG_ATC_MENU_OPENED: "atc_menu"
  MSG_ATC_MENU_CLOSED: "menu_closed"
  MSG_ATC_INVALID_OPTION: "invalid_option"
  MSG_ATC_PRESS_ESC: "press_escape_to_close"

  # Menu options (simple cockpit announcements with Samantha voice)
  MSG_ATC_OPTION_REQUEST_STARTUP: "menu_request_startup"
  MSG_ATC_OPTION_REQUEST_ATIS: "menu_request_atis"
  MSG_ATC_OPTION_REQUEST_TAXI: "menu_request_taxi"
  MSG_ATC_OPTION_REQUEST_TAKEOFF: "menu_request_takeoff"
  MSG_ATC_OPTION_READY_DEPARTURE: "menu_report_ready"
  MSG_ATC_OPTION_CHECKIN_DEPARTURE: "menu_request_departure"
  MSG_ATC_OPTION_REPORT_ALTITUDE: "menu_report_altitude"
  MSG_ATC_OPTION_REQUEST_FLIGHT_FOLLOWING: "menu_request_flight_following"
  MSG_ATC_OPTION_REPORT_POSITION: "menu_report_position"
  MSG_ATC_OPTION_REQUEST_LANDING: "menu_request_landing"
  MSG_ATC_OPTION_ACKNOWLEDGE: "menu_acknowledge"
  MSG_ATC_OPTION_BACK: "menu_back"
